#!/usr/bin/env node
/**
 * Writes the JSON-LD each route's registry entry declares into its page.
 *
 * STATIC, NOT RUNTIME. assets/js/schema.js documents a browser usage where the
 * page injects the blocks itself. That cannot work here: nine of the ten pages
 * ship no <script> tag at all, so a runtime injection would emit nothing on
 * them. The blocks are written into the HTML instead, between markers, and
 * check:json-ld regenerates and compares so they cannot drift from the
 * registry.
 *
 * The registry decides what each page gets — `schema: [...]` in
 * src/config/routes.js — and this script only renders it. Adding a type to a
 * route's entry and re-running is the whole workflow.
 *
 * Idempotent: it replaces the marked block, so running it twice is a no-op.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const { ROUTES } = require('../src/config/routes.js');
const {
  buildOrganizationSchema,
  buildRealEstateAgentSchema,
  buildBreadcrumbListSchema,
} = require('../assets/js/schema.js');

export const START = '<!-- json-ld:generated by scripts/generate-json-ld.mjs — do not edit by hand -->';
export const END = '<!-- /json-ld -->';

const fileFor = (path) => (path === '/' ? 'index.html' : `${path.replace(/^\//, '')}index.html`);

/** Short label for a breadcrumb: the registry title with the brand removed. */
const crumbName = (route) => {
  if (route.path === '/') return 'Home';
  return route.title
    .replace(/\s*\|\s*TD Realty Ohio\s*$/i, '')
    .replace(/\s*TD Realty Ohio\s*$/i, '')
    .trim();
};

/** Walks `parent` up to the root, ending with the page itself. */
export const trailFor = (route, byPath) => {
  const trail = [];
  let current = route;
  const seen = new Set();
  while (current && !seen.has(current.path)) {
    seen.add(current.path);
    trail.unshift({ name: crumbName(current), path: current.path });
    current = current.parent ? byPath.get(current.parent) : null;
  }
  return trail;
};

export function blocksFor(route, byPath) {
  const declared = route.schema || [];
  const blocks = [];

  for (const type of declared) {
    if (type === 'Organization') {
      blocks.push(buildOrganizationSchema());
    } else if (type === 'RealEstateAgent') {
      blocks.push(buildRealEstateAgentSchema({ description: route.description }));
    } else if (type === 'BreadcrumbList') {
      const trail = trailFor(route, byPath);
      // A breadcrumb list containing only the current page describes no path.
      if (trail.length > 1) blocks.push(buildBreadcrumbListSchema(trail));
    } else {
      throw new Error(`${route.path} declares schema "${type}", which nothing knows how to build`);
    }
  }
  return blocks;
}

export function renderBlocks(blocks) {
  if (!blocks.length) return '';
  const scripts = blocks
    .map((block) => `<script type="application/ld+json">\n${JSON.stringify(block, null, 2)}\n</script>`)
    .join('\n');
  return `${START}\n${scripts}\n${END}`;
}

/** Replaces an existing marked block, or inserts one before </head>. */
export function inject(html, rendered) {
  const existing = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n?`);
  const stripped = html.replace(existing, '');
  if (!rendered) return stripped;
  if (!stripped.includes('</head>')) throw new Error('page has no </head>');
  return stripped.replace('</head>', `${rendered}\n</head>`);
}

async function main() {
  const byPath = new Map(ROUTES.map((route) => [route.path, route]));
  let written = 0;

  for (const route of ROUTES) {
    const file = join(ROOT, fileFor(route.path));
    const html = await readFile(file, 'utf-8');
    const rendered = renderBlocks(blocksFor(route, byPath));
    const next = inject(html, rendered);
    if (next !== html) {
      await writeFile(file, next);
      written += 1;
    }
    const types = (route.schema || []).join(', ') || 'none';
    console.log(`  ${route.path.padEnd(17)} ${types}`);
  }

  console.log(`\n[json-ld] ${written} page(s) updated, ${ROUTES.length} checked.`);
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
